on: [push, pull_request]

name: CI

jobs:
  build_and_test:
    name: Cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
